import React from "react"
import { Button } from "../components/controls/button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/ahZy0r2O6hcR2Wt6HP3U9Y/Untitled?node-id=1%3A4",
  {
    props: {},
    example: (props) => <Button />,
  },
)
