import React from "react";
import FWButton from "./FWButton";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FWButton,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7003-72901&t=hRbPZyJGMSjyNYEW-4",
  {
    props: {
      label: figma.string("label"), // Map label to a string property
      variant: figma.enum("variant", {
        primary: 'primary',
        secondary: 'secondary',
      }), // Map variant to an enum
      disabled: figma.enum("state", {
        disabled: true,
      }), // Map isDisabled to a boolean
    },
    example: (props) => (
      <FWButton
      label={props.label}
      variant={props.variant}
      disabled={props.disabled}
      onPress={() => {
      }}
    >
    </FWButton>
    ),
  },
);