import React from "react"
import FWButton from "./FWButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FWButton,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7003-72901&m=dev",
  {
    props: {
      label: figma.string("label"),
      state: figma.enum("state", {
        default: "default",
        pressed: "pressed",
      }),
      isDisabled: figma.boolean("isDisabled"),
    },
    example: (props) => <FWButton
      label={props.label}
      onPress={() => {}}
      disabled={props.isDisabled}
      variant={props.state}
    />

  },
)
