import React from "react"
import ActionBar from "./ActionBar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ActionBar,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7108%3A4538",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "topButton": figma.boolean('topButton'),
      // "midButton": figma.boolean('midButton'),
      // "bottomButton": figma.boolean('bottomButton'),
      // "isEmpty": figma.boolean('isEmpty')
    },
    example: (props) => <ActionBar />,
  },
)
