import React from "react"
import ActionBar from "./ActionBar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ActionBar,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7108%3A4538",
  {
    props: {
      topButton: figma.boolean('topButton', {
        true: figma.instance("topSlot"), // Map topButton to an instance
        false: undefined
      }),

      midButton: figma.boolean('midButton', {
        true: figma.instance("midSlot"), // Map midButton to an instance
        false: undefined
      }),

      bottomButton: figma.boolean('bottomButton', {
        true: figma.instance("bottomSlot"), // Map bottomButton to an instance
        false: undefined
      }),
      isEmpty: figma.boolean("isEmpty", {
        true: true, // Map isEmpty to an instance
        false: undefined
      }),

    },
    example: (props) => (
      <ActionBar
        topButton={props.topButton}
        midButton={props.midButton}
        isEmpty={props.isEmpty}
        bottomButton={props.bottomButton}
      />
    ),
  },
)
