import React from "react"
import BottomContext from "./BottomContext"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  BottomContext,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7092%3A3530",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      state: figma.enum("state", {
        maxButton: "maxButton",
        empty: "empty",
        payment: "payment",
        addPayment: "addPayment",
      }),
    },
    example: (props) => <BottomContext state={props.state} />,
  },
)
