import React from "react"
import CurrencyInput from "./CurrencyInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CurrencyInput,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7093%3A3821",
  {
    props: {
      topSlot: figma.children(["Top context"]),
      bottomSlot: figma.children(["Bottom context"]),
      amount: figma.string("amount"),
    },
    example: (props) => <CurrencyInput amount={props.amount} topSlot={props.topSlot} bottomSlot={props.bottomSlot} />
  },
)
