import React from "react"
import TopContext from "./TopContext"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TopContext,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7092%3A3551",
  {
    props: {
       "content": figma.enum('content', {
         "empty": "empty",
         "iconLabel": "iconLabel",
         "label": "label"
       }),
       icon: figma.instance("icon"),
       label: figma.string("label"),
    },
     example: (props) => {
          return (
            <TopContext
              label={props.label}
              icon={props.icon}
            >
            </TopContext>
          );
     }
  },
);
