import React from "react";
import StackControl from "./StackControl";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  StackControl,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7094%3A4042",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("variant", {
        left: "left",
        right: "right",
      }),
      // map instances into the slot props via booleans
      leadingSlot: figma.boolean("leadingIcon", {
        true: figma.instance("leadingSlot"),
        false: undefined,
      }),
      trailingSlot: figma.boolean("trailingIcon", {
        true: figma.instance("trailingSlot"),
        false: undefined,
      }),
    },
    example: ({ variant, leadingSlot, trailingSlot }) => (
      <StackControl
        variant={variant}
        leadingSlot={leadingSlot}
        trailingSlot={trailingSlot}
      />
    ),
  }
);
