import React from "react"
import ActionTile from "./ActionTile"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ActionTile,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7041%3A3059",
  {
    props: {
      label: figma.string("label"), // Map label to a string property
      leadingIcon: figma.boolean("leadingIcon", {
        true: figma.instance("leadingSlot"),
        false: undefined,
      }), // Map leadingIcon to a boolean
      trailingIcon: figma.boolean("trailingIcon", {
        true: figma.instance("trailingSlot"),
        false: undefined,
      }), // Map trailingIcon to a boolean
      selected: figma.boolean("selected"), // Map state to an enum with all possible values
    },

    example: (props) => {
      return (
        <ActionTile
          selected={props.selected}
          leadingSlot={props.leadingIcon}
          trailingSlot={props.trailingIcon}
        >
          {props.label}
        </ActionTile>
      );
    },
  },
)
