import React from "react";
import CustomKeyboard from "./KeyboardButton";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */



figma.connect(
  CustomKeyboard,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7017%3A3401",
  {
    props: {
      icon: figma.string("icon"), // Use a string for icon (e.g., icon name or URL)
    },
    example: ({ icon }) => (
      <CustomKeyboard
        variant="iconOnly"
        icon={icon}
        onPress={() => {}}
      />
    ),
  }
);

figma.connect(
  CustomKeyboard,
  "https://www.figma.com/design/P2LVZrKxzm5EdYUKyZsXDA/%F0%9F%94%B5--MCP?node-id=7017%3A3405",
  {
    props: {
      label: figma.string("label"), // Only relevant for textOnly
    },
    example: ({ label }) => (
      <CustomKeyboard
        variant="textOnly"
        onPress={() => {}
      }
      >
        {label} 
      </CustomKeyboard>
    ),
  }
);
